- setup.py
- src/DMXGui.py
- src/Network.py
- src/cli/bankset_command.py
- src/cli/cli_context.py
- src/cli/command.py
- src/cli/help_command.py
- src/cli/list_command.py
- src/cli/remote_control_port.py
- src/cli/select_command.py
- src/model/color_hsi.py
- src/model/control_desk.py
This pull request implements a basic CLI port for remote management. Furthermore it implements the management of control desk input configuration as its first command.
Further changes:
* Append creation of control port object in DMXGui
* Implement message queuing in Network.py
Remaining bugs:
Features that will be added later:
* Management of running scene
* Updating filter parameters
* Listing filters
* Updating input column settings
* listing scenes
> Cli and control port

- src/file/write.py
- src/model/broadcaster.py
- src/network.py
- src/view/console_mode/console_scene_selector.py
- src/view/main_window.py
- src/view/show_mode/node_editor.py
Added menu entries to switch mode
Switches to filter mode when opening filter window
> Switch fish mode

- src/network.py
- src/view/show_mode/nodes/adapters.py
enter_ scene didnt work, or is this useless because scene switches (in show-ui branch) when selecting them
> fix: enter scene sending message

- src/file/showfile_dialogs.py
- src/view/main_window.py
- src/view/show_mode/editor/scenetab.py
- src/view/show_mode/editor/showmanager.py
In an attempt to start the unification of the UX I began to move and rename a few buttons.
> Renaming and moving of buttons

- src/view/show_mode/editor/nodes/filter_node_library.py
- src/view/show_mode/editor/nodes/impl/adapters.py
- src/view/show_mode/editor/nodes/type_to_node_dict.py
added filter: range of float to range of 8bit, 16bit and float
added filter: combine two 8bit values to 16bit
added filter: map 8bit to 16bit
> add: range filter and 8bit to 16bit mapping and combine two 8bit values

- src/model/filter.py
- src/model/virtual_filters/__init__.py
Added the virtual filter abstract class in order to be able to parallelize development again.
> add: virtual filter abstract class

- src/controller/file/read.py
- src/controller/file/serializing/filter_serialization.py
- src/controller/file/serializing/fish_optimizer.py
- src/controller/file/serializing/general_serialization.py
- src/controller/file/serializing/scene_serialization.py
- src/controller/file/transmitting_to_fish.py
- src/controller/file/write.py
- src/controller/utils/process_notifications.py
- src/view/main_window.py
- src/view/show_mode/editor/show_browser/show_browser.py
- fixes #123
- Implements Process notifier (as it was handy during debugging.
> fix: show file serialization

- src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
- src/view/show_mode/editor/nodes/type_to_node_dict.py
The changes that we talked about
> fix: auto show commit on preview

- src/model/virtual_filters/auto_tracker_filter.py
- src/view/show_mode/editor/filter_settings_item.py
- src/view/show_mode/editor/node_editor_widgets/cue_editor/channel_label.py
- src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
- src/view/show_mode/editor/node_editor_widgets/cue_editor/timeline_content_widget.py
- src/view/show_mode/editor/node_editor_widgets/cue_editor/timeline_editor.py
- src/view/show_mode/editor/nodes/impl/effects.py
- src/view/show_mode/editor/show_ui_widgets/__init__.py
- src/view/show_mode/editor/show_ui_widgets/cue_control.py
However, as of now, not all tasks of issue #12 have been adressed.
> Various cue editor improvements

- src/view/show_mode/editor/show_ui_widgets/__init__.py
The instantiation of show ui widgets needs to be changed as well.
> fix: cue show widget instantiation

- src/controller/ofl/fixture.py
- src/model/file_support/cue_state.py
- src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
- src/view/show_mode/editor/nodes/impl/effects.py
added an input to be able to scale the input time
> Cue filter scale time

- src/controller/file/read.py
- src/controller/network.py
- src/model/broadcaster.py
- src/model/ui_configuration.py
- src/view/main_window.py
- src/view/misc/settings/settings_dialog.py
Adds a dialog to change the settings of a show file.
> Show file settings

- requirements.txt
- src/gl_init.py
- src/main.py
- src/resources/logo.png
- src/resources/splash.png
- src/view/main_window.py
As we've talked about: Here are the changes from the color picker branch regarding the initialization.
> add: changes to main from color picker branch

- Dockerfile
> remove requirements.txt

- src/view/show_mode/editor/filter_flowchart.py
- src/view/show_mode/editor/nodes/base/aggregating_filter_node.py
- src/view/show_mode/editor/showmanager.py
Fix Bug #197 and remove an unused second instance of the filter node library while we're at it.
> fix: issue #197

- src/controller/network.py
- src/view/show_mode/editor/node_editor_widgets/import_vfilter_settings_widget.py
- src/view/utility_widgets/filter_selection_widget.py
Fix bugs regarding the import vfilter and improve it
> 179 improve import vfilter

- src/controller/network.py
- src/model/board_configuration.py
- src/view/show_mode/editor/editor_tab_widgets/bankset_tab.py
- src/view/show_mode/editor/editor_tab_widgets/ui_widget_editor/_widget_holder.py
- src/view/show_mode/editor/filter_settings_item.py
- src/view/show_mode/editor/node_editor_widgets/column_select.py
- src/view/show_mode/editor/nodes/impl/faders.py
- src/view/show_mode/show_ui_widgets/debug_viz_widgets.py
- src/view/utility_widgets/fader_column_selector.py
This still needs to be tested as there might be further issues.
> fix: color columns not registering an update listener

- src/view/utility_widgets/box_grid_renderer.py
- test/manual_test_box_render_widgets.py
There are a couple of issues that require a floating box rendering widget. For example issue #190 or the patching menu.
As we'd like to use those, I'll implement one.
> add: floating box widget drawing

- pyproject.toml
- src/controller/cli/remote_control_port.py
- src/controller/network.py
- src/model/broadcaster.py
- src/model/control_desk.py
- src/model/events.py
- src/model/ui_configuration.py
- src/view/main_window.py
- src/view/show_mode/editor/show_browser/fixture_to_filter.py
next part of ruff clarification
> remove unessasary global 

- src/view/show_mode/editor/node_editor_widgets/cue_editor/channel_input_dialog.py
- src/view/show_mode/editor/node_editor_widgets/cue_editor/cue_editor_widget.py
- src/view/show_mode/editor/node_editor_widgets/sequencer_editor/widget.py
> add: multi channel add dialog
